name: lint_test_deploy
on: push
jobs:
  LTD_Job:
    runs-on: ubuntu-latest
    steps:
      - name: Lint-Job
        run: |
          echo "Now Running Lint"
          lint "eslint --ext .jsx --fix src"
